<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="17807" started-at="2018-05-15T06:48:49Z" finished-at="2018-05-15T06:49:06Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="17807" started-at="2018-05-15T06:48:49Z" finished-at="2018-05-15T06:49:06Z">
      <class name="Tests.FreeCRMTest">
        <test-method status="PASS" signature="setUpExtent()[pri:0, instance:Tests.FreeCRMTest@3bfdc050]" name="setUpExtent" is-config="true" duration-ms="141" started-at="2018-05-15T06:48:49Z" finished-at="2018-05-15T06:48:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpExtent -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:Tests.FreeCRMTest@3bfdc050]" name="setUp" is-config="true" duration-ms="15206" started-at="2018-05-15T06:48:49Z" finished-at="2018-05-15T06:49:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="titleTest()[pri:0, instance:Tests.FreeCRMTest@3bfdc050]" name="titleTest" duration-ms="40" started-at="2018-05-15T06:49:04Z" finished-at="2018-05-15T06:49:04Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [RM software in the cloud powers sales and customer service] but found [Free CRM software in the cloud powers sales and customer service]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [RM software in the cloud powers sales and customer service] but found [Free CRM software in the cloud powers sales and customer service]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at Tests.FreeCRMTest.titleTest(FreeCRMTest.java:74)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- titleTest -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:Tests.FreeCRMTest@3bfdc050]" name="tearDown" is-config="true" duration-ms="1949" started-at="2018-05-15T06:49:04Z" finished-at="2018-05-15T06:49:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=titleTest status=FAILURE method=FreeCRMTest.titleTest()[pri:0, instance:Tests.FreeCRMTest@3bfdc050] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Tests.FreeCRMTest@3bfdc050]" name="afterTest" is-config="true" duration-ms="422" started-at="2018-05-15T06:49:06Z" finished-at="2018-05-15T06:49:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- Tests.FreeCRMTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
